### ISSUE TITLE
Prerequisites page - Number of VMs created for you

### ISSUE THREAD

**Issue by mflannery** [johnsimcall/redhatgov.github.io#4]
This says that 4 VMs are created for us and a 5th will be created as well.  It lists the RHV Manager as one of those VMs.  I think this is a little confusing.  Are we talking about the Ravello VMs or the VMs that are created inside of RHHI?  I would rather we separate those out.  4 VMs are created for you, 3 hypervisors and 1 admin.

**Comment by rickmanley-nc** [comment]
Good point, looking this back over, the intention of detailing the workshop environment is to show the students what the Ravello environment looks like. Since the RHV Manager VM is not in the workshop environment at the beginning, it's not relevant yet.

That said, in the topology section, we're covering how a RHHI-V environment looks **without** the context of the Ravello cloud. Should we include a graphic that includes the Admin server? We could even take a pic of the blueprint in Ravello as we talk about it.

I've gone ahead and updated the wording with the following though:


## **The Workshop Environment**

- Login credentials are either **root/redhat1** or **admin/redhat1**
- 4x Virtual Machines have been created for you:
 - 1x Admin node (provides DNS, DHCP, NFS, VNC, and repos to the rest of the environment)
 - 3x Hypervisors with local storage
  - NIC1: rhhi1.localdomain / NIC2: rhhi1-gluster
  - NIC1: rhhi2.localdomain / NIC2: rhhi2-gluster
  - NIC1: rhhi3.localdomain / NIC2: rhhi3-gluster

**Comment by rickmanley-nc** [comment]
updated language, referenced admin as jumphost, and rearranged "Workshop Environment"
